# Generated by Django 4.1.7 on 2023-04-08 17:52

import ApiRest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('title_photo', models.ImageField(blank=True, upload_to=ApiRest.models.get_category_photo_path, verbose_name='Титулное фото')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('promo_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Промокод')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'сlient',
                'ordering': ['-data_created', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('product_number', models.IntegerField(unique=True, verbose_name='Номер продукта')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('is_my_work', models.BooleanField(default=False, verbose_name='Наш продукт')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ['-id', 'date_added', 'product_number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_prod', models.IntegerField(default=1, verbose_name='Количество')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.client', verbose_name='Клиент')),
                ('product_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_active', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая Цена')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'История цен',
                'verbose_name_plural': 'История цен',
                'db_table': 'history_price',
                'ordering': ['-id', 'date_added', 'price_active', 'price_old'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=ApiRest.models.get_upload_path, verbose_name='Фото')),
                ('is_title', models.BooleanField(default=False, verbose_name='Главный постер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'db_table': 'gallery',
                'ordering': ['-id', 'product'],
            },
        ),
    ]
