# Generated by Django 4.1.7 on 2023-04-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyprice',
            name='is_action',
            field=models.BooleanField(default=False),
        ),
    ]
