# Generated by Django 4.1.7 on 2023-04-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0002_historyprice_is_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8, verbose_name='Промокод')),
                ('discount', models.PositiveIntegerField(max_length=3, verbose_name='Скидка')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promo_code',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='historyprice',
            name='is_action',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='client',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.promocode', verbose_name='Промокод'),
        ),
    ]
