# Generated by Django 4.1.7 on 2023-04-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0003_promocode_alter_historyprice_is_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count_prod',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.PositiveIntegerField(default=1, verbose_name='Скидка'),
        ),
    ]
